from .streamlined import (
    SECTION_WRITER_SYSTEM_PROMPT,
    SECTION_WRITER_USER_PROMPT,
    STRUCTURE_WRITER_LONG_PROMPT,
    STRUCTURE_WRITER_SHORT_PROMPT,
    TITLE_WRITER_SYSTEM_PROMPT,
    TITLE_WRITER_USER_PROMPT
)

from .advanced import (
    ADVANCED_SECTION_WRITER_SYSTEM_PROMPT,
    ADVANCED_SECTION_WRITER_USER_PROMPT,
    ADVANCED_STRUCTURE_WRITER_LONG_PROMPT,
    ADVANCED_STRUCTURE_WRITER_SHORT_PROMPT,
    ADVANCED_TITLE_WRITER_SYSTEM_PROMPT,
    ADVANCED_TITLE_WRITER_USER_PROMPT
)